services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=investimentos
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - "3306"